import type { TraceData } from '../types';
import { magDb, phaseDeg } from '../utils/sparams';

/** Export as Touchstone S2P (S11 + S21, S12/S22 = 0) */
export function toS2P(s11: TraceData, s21: TraceData): string {
  const lines: string[] = [
    '! Generated by S-Parameter Analyzer',
    '# Hz S RI R 50',
    '! Freq  Re(S11)  Im(S11)  Re(S21)  Im(S21)  Re(S12)  Im(S12)  Re(S22)  Im(S22)',
  ];
  const n = Math.min(s11.points.length, s21.points.length);
  for (let i = 0; i < n; i++) {
    const p11 = s11.points[i];
    const p21 = s21.points[i];
    lines.push(
      `${Math.round(p11.freq)}  ${p11.re.toFixed(8)}  ${p11.im.toFixed(8)}` +
      `  ${p21.re.toFixed(8)}  ${p21.im.toFixed(8)}` +
      `  0  0  0  0`,
    );
  }
  return lines.join('\n');
}

/** Export as CSV with magnitude/phase columns */
export function toCSV(s11: TraceData, s21: TraceData): string {
  const header = 'Freq_Hz,S11_re,S11_im,S11_dB,S11_deg,S21_re,S21_im,S21_dB,S21_deg';
  const n = Math.min(s11.points.length, s21.points.length);
  const rows = [header];
  for (let i = 0; i < n; i++) {
    const p11 = s11.points[i];
    const p21 = s21.points[i];
    rows.push(
      [
        Math.round(p11.freq),
        p11.re.toFixed(8), p11.im.toFixed(8),
        magDb(p11.re, p11.im).toFixed(4), phaseDeg(p11.re, p11.im).toFixed(4),
        p21.re.toFixed(8), p21.im.toFixed(8),
        magDb(p21.re, p21.im).toFixed(4), phaseDeg(p21.re, p21.im).toFixed(4),
      ].join(','),
    );
  }
  return rows.join('\n');
}

export function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
